### ISSUE TITLE
Feature request: Offset scanning

### ISSUE THREAD

**Issue by jbhunter21** [khaytsus/gqrx-scan#15]
Placing this feature request here, knowing that the feature is not available in gqrx remote control at the moment but if you find it useful you could forward it to csete/gqrx?

Feature:
Would be nice to have a center-frequency set for an example 127.500Mhz and then scan through different frequencies within the selected bandwidth only using the filter-offset.
If used with for an example a hackRF that has support for a 20Mhz bandwidth you could scan through the whole 19Mhz airband (118Mhz-137Mhz) in a split second when you take away the latency of having your receiver retune to every frequency / channel that you are interested in.

Only concern here that I see is that gqrx remote control might not be that fast due to telnet?
I've seen this feature in SDR# with a scanning plugin an the greatest benefit was that because it could scan frequencies so fast you never lost the first second or so off transmission when recording.

Best regards
Johan (jbhunter21)

**Comment by khaytsus** [comment]
I like the idea, but except as a single command instructing GQRX to do so, the telnet interface would be way too slow for this.  Currently I have to wait about .3s in order to determine if there is a signal reliably.  I can probably scan with squelch open much faster, but without any signal detection.  

Either way, I'm sure that this should be a function request in https://github.com/csete/gqrx and I'd recommend you log it there so you see the feedback etc.  Anything he adds to the TCP interface that's useful for this script I'll implement.  :)

In the meanwhile, would it be useful to scan without signal detection?  I wouldn't think so, as you'd just hear there was traffic on a frequency without it stopping there.  That would be easy for me to do without any upstream changes but I don't think it'd be very useful.

**Comment by jbhunter21** [comment]
I agree with you that it's of no use without any signal detection.
I will create a log in https://github.com/csete/gqrx and hopefully we get something good out of it :)

**Comment by khaytsus** [comment]
Cool, I'll close this for now but I'll keep an eye out for his interface.  Long term, it'd be nice for GQRX to have scanning built-in, as I think it could do it a lot faster and better than I can do remotely.

**Comment by jbhunter21** [comment]
Got an answer from csete and he says that this already is implemented. Now that I think of it, he's right. If you change to a frequency within the current bandwidth it only moves the filter offset and keeping the center-frequency locked.
So as long as gqrx stick with telnet for remote controlling and not implementing its own scanner it seems like scanning today is close to as effective as it can be I guess? :/

**Comment by khaytsus** [comment]
Well, yes, I agree that what he says is absolutely correct; he's not going to change the hardware tuning frequency if tuned within the bandwidth.  However, what you're really looking for is a fast scan method which isn't currently possible via the TCP interface.  I'm not sure if that's really a separate request (ie:  Scanning in GQRX) or changes to the TCP interface.

I don't know what limitations the TCP interface could have as an absolute max interaction speed but currently I've never been able to reliably detect the signal strength of the current frequency any faster than about .3s.

I assume GQRX is not changing the hardware frequency if the TCP remote tells it to change frequency, but that's pretty easy to see..  Watch the GQRX screen and see if you go between two frequencies and the offset is changing and the center frequency remains static.  I can look when I'm at home if you don't have a chance.  If by chance GQRX is re-tuning, there's improvements that could be made there I'd think.

Maybe the feature request is more along the lines of at least a minimal scanning ability in GQRX.  I only see one really relevant request for scanning in his issues list, maybe you should log a new one?  The one that's there is from 2012.  Look at it and see if you think yours would be a duplicate but otherwise it's something that'd be really nice to have in GQRX and if it were doing it natively I imagine we could get much faster scanning than poking every frequency via TCP remote and waiting for results.  I think ultimately there would be a scan speed limit but I'm reasonably sure it'd be faster than it can be today (3freq/sec).  

I do have one small suggestion; make sure you're using the right step in scanning.  It sounds like you're scanning air band but that might just be your example...  I think the air band is pretty wide channels, so setting the step to the right channel width would certainly speed up scanning of the "channels" in the air band.  I believe the width in the US is 25khz, the default scan step in my script is 1khz, so it potentially is scanning 25 times for each channel.  IE:

gqrx-scan --type scan --start 118e6 --end 136e6 --mode AM --delaylevel=-40 --delaytime 10 --step 25000

Still 16 seconds per mhz, so not super fast, but if you didn't have step specified this would definitely make things a lot slower than necessary.  :)
